---

- name: Configure Access Leaf Group 9
  hosts: access_leaf_group_9
  tasks:

  - name: Create VLANs
    ios_vlans:
      config:
       - name: vlan26
         vlan_id: 28
         state: active
         shutdown: disabled
       - name: vlan28
         vlan_id: 28
         state: active
         shutdown: disabled

  - name: Setting switchport mode turnk and access ports
    cisco.ios.ios_l2_interfaces:
      config:
      - name: GigabitEthernet0/1
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/2
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/3
        mode: access
        access:
          vlan: 10
      - name: GigabitEthernet1/0
        mode: access
        access:
          vlan: 12

- name: Configure Access Leaf Group 10
  hosts: access_leaf_group_10
  tasks:

  - name: Create VLANs
    ios_vlans:
      config:
       - name: vlan30
         vlan_id: 30
         state: active
         shutdown: disabled
       - name: vlan32
         vlan_id: 32
         state: active
         shutdown: disabled

  - name: Setting switchport mode turnk and access ports 
    cisco.ios.ios_l2_interfaces:
      config:
      - name: GigabitEthernet0/1
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/2
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/3
        mode: access
        access:
          vlan: 30
      - name: GigabitEthernet1/0
        mode: access
        access:
          vlan: 32
