---

- name: Configure Access Leaf Group 1
  hosts: access_leaf_group_1 
  tasks:

  - name: Create and enable VLANs 2 and 4
    ios_vlans:
      config:
       - name: vlan2
         vlan_id: 2
         state: active
         shutdown: disabled
       - name: vlan4
         vlan_id: 4
         state: active
         shutdown: disabled

  - name: Setting switchport mode turnk and set access ports
    cisco.ios.ios_l2_interfaces:
      config:
      - name: GigabitEthernet0/1
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/2
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/3
        mode: access
        access:
          vlan: 2
      - name: GigabitEthernet1/0
        mode: access
        access:
          vlan: 4

- name: Configure Access Leaf Group 2
  hosts: access_leaf_group_2
  tasks:

  - name: Create VLANs and enable VLANs 6 and 8
    ios_vlans:
      config:
       - name: vlan6
         vlan_id: 6
         state: active
         shutdown: disabled
       - name: vlan8
         vlan_id: 8
         state: active
         shutdown: disabled

  - name: Setting switchport mode turnk and set access ports 
    cisco.ios.ios_l2_interfaces:
      config:
      - name: GigabitEthernet0/1
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/2
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/3
        mode: access
        access:
          vlan: 6
      - name: GigabitEthernet1/0
        mode: access
        access:
          vlan: 8




