---

- name: Task to see config
  hosts: access 
  tasks:

  - name: Create VLANs
    ios_vlans:
      config:
       - name: vlan3
         vlan_id: 3
         state: active
         shutdown: disabled
       - name: vlan5
         vlan_id: 5
         state: active
         shutdown: disabled

  - name: Setting switchport mode turnk
    cisco.ios.ios_l2_interfaces:
      config:
      - name: GigabitEthernet0/1
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/3
        mode: access
        access:
          vlan: 3
      - name: GigabitEthernet1/0
        mode: access
        access:
          vlan: 5 
