---

- name: Configure Access Leaf Group 3
  hosts: access_leaf_group_7
  tasks:

  - name: Create and enable VLANs 18 and 20
    ios_vlans:
      config:
       - name: vlan18
         vlan_id: 18
         state: active
         shutdown: disabled
       - name: vlan20
         vlan_id: 20
         state: active
         shutdown: disabled

  - name: Setting switchport mode turnk and access ports
    cisco.ios.ios_l2_interfaces:
      config:
      - name: GigabitEthernet0/1
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/2
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/3
        mode: access
        access:
          vlan: 18
      - name: GigabitEthernet1/0
        mode: access
        access:
          vlan: 20

- name: Configure Access Leaf Group 4
  hosts: access_leaf_group_8
  tasks:

  - name: Create and enable VLANs 22 and 24
    ios_vlans:
      config:
       - name: vlan22
         vlan_id: 22
         state: active
         shutdown: disabled
       - name: vlan24
         vlan_id: 24
         state: active
         shutdown: disabled

  - name: Setting switchport mode turnk and access ports 
    cisco.ios.ios_l2_interfaces:
      config:
      - name: GigabitEthernet0/1
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/2
        mode: trunk
        trunk:
          encapsulation: dot1q
      - name: GigabitEthernet0/3
        mode: access
        access:
          vlan: 22
      - name: GigabitEthernet1/0
        mode: access
        access:
          vlan: 24
