---

- name: Configure Fireall-1
  hosts: firewall-1
  become: yes
  gather_facts: no
  tasks:

  - name: Configure GigabitEthernet0/0  
    cisco.asa.asa_config:
      lines:
      - ip address 20.0.0.122 255.255.255.0
      - nameif inside
      - security-level 100
      - no shutdown
      parents: interface GigabitEthernet0/0  
      
  - name: Configure GigabitEthernet0/1
    cisco.asa.asa_config:
      lines:
      - ip address 200.0.1.1 255.255.255.0
      - nameif outside
      - security-level 0
      - no shutdown
      parents: interface GigabitEthernet0/1

  - name: Configure static route
    cisco.asa.asa_config:
      lines:
      - route outside 0.0.0.0 0.0.0.0 200.0.1.2

 - name: Configure inside net VLAN10
    cisco.asa.asa_config:
      lines:
      - subnet 192.168.10.0 255.255.255.0
      - nat (inside,outside) dynamic interface
      parents: object network INSIDE-NET-VLAN10

  - name: Configure inside net VLAN12
    cisco.asa.asa_config:
      lines:
      - subnet 192.168.12.0 255.255.255.0
      - nat (inside,outside) dynamic interface
      parents: object network INSIDE-NET-VLAN12

  - name: Configure icmp policy
    cisco.asa.asa_config:
      lines:
      - inspect icmp
      parents: [policy-map global_policy, class inspection_default]
