---

#################################
### Configure core interfaces ###
#################################

- name: Task to see config
  hosts: core1
  tasks:

  - name: Configure layer3 interfaces to core
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        description: Core1 to Core2 interface
        mode: layer3
      - name: Ethernet1/2
        description: Core1 to Core4 interface
        mode: layer3
      - name: Ethernet1/3
        description: Core1 to Core3 interface
        mode: layer3

  - name: Merge provided configuration with device configuration.
    cisco.nxos.nxos_l3_interfaces:
      config:  
      - name: Ethernet1/1
        ipv4:
        - address: 10.0.1.1/24
      - name: Ethernet1/2
        ipv4:
        - address: 10.0.1.2/24
      - name: Ethernet1/3
        ipv4:
        - address: 10.0.1.3/24

  - name: Bring up interfaces
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        enabled: true
      - name: Ethernet1/2
        enabled: true
      - name: Ethernet1/3
        enabled: true









        
