---

#################################
### Configure core1 interfaces ###
#################################

- name: Task to see config
  hosts: core1
  tasks:

  - name: Configure interfaces to layer3
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        description: Core1 to Core2 interface
        mode: layer3
      - name: Ethernet1/2
        description: Core1 to Core4 interface
        mode: layer3
      - name: Ethernet1/3
        description: Core1 to Core3 interface
        mode: layer3
      - name: Ethernet1/4
        description: Core1 to Dist3 interface
        mode: layer3
      - name: Ethernet1/5
        description: Core1 to Dist4 interface
        mode: layer3
      - name: Ethernet1/6
        description: Core1 to Dist2 interface
        mode: layer3
      - name: Ethernet1/7
        description: Core1 to Dist1 interface
        mode: layer3
      - name: Ethernet1/8
        description: Core1 to Dist12 interface
        mode: layer3
      - name: Ethernet1/9
        description: Core1 to Dist11 interface
        mode: layer3

  - name: Configure layer 3 interfaces
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: Ethernet1/1
        ipv4:
        - address: 20.0.0.101/30
      - name: Ethernet1/2
        ipv4:
        - address: 20.0.0.97/30
      - name: Ethernet1/3
        ipv4:
        - address: 20.0.0.113/30
      - name: Ethernet1/4
        ipv4:
        - address: 20.0.0.22/30
      - name: Ethernet1/5
        ipv4:
        - address: 20.0.0.30/30
      - name: Ethernet1/6
        ipv4:
        - address: 20.0.0.10/30
      - name: Ethernet1/7
        ipv4:
        - address: 20.0.0.2/30
      - name: Ethernet1/8
        ipv4:
        - address: 20.0.0.90/30
      - name: Ethernet1/9
        ipv4:
        - address: 20.0.0.82/30
        

  - name: Bring up interfaces
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        enabled: true
      - name: Ethernet1/2
        enabled: true
      - name: Ethernet1/3
        enabled: true
      - name: Ethernet1/4
        enabled: true
      - name: Ethernet1/5
        enabled: true
      - name: Ethernet1/6
        enabled: true
      - name: Ethernet1/7
        enabled: true
      - name: Ethernet1/8
        enabled: true
      - name: Ethernet1/9
        enabled: true
        
  - name: Configure static routes to distribution and core
    cisco.nxos.nxos_static_routes:
      config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: 192.168.2.0/24
            next_hops:
            - interface: eth1/6
              forward_router_address: 20.0.0.9
            - interface: eth1/7
              forward_router_address: 20.0.0.1
          - dest: 192.168.4.0/24
            next_hops:
            - interface: eth1/7
              forward_router_address: 20.0.0.1
            - interface: eth1/6
              forward_router_address: 20.0.0.9
          - dest: 192.168.6.0/24
            next_hops:
            - interface: eth1/7
              forward_router_address: 20.0.0.1
            - interface: eth1/6
              forward_router_address: 20.0.0.9
          - dest: 192.168.8.0/24
            next_hops:
            - interface: eth1/7
              forward_router_address: 20.0.0.1
            - interface: eth1/6
              forward_router_address: 20.0.0.9
          - dest: 192.168.10.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.21
            - interface: eth1/5
              forward_router_address: 20.0.0.29
          - dest: 192.168.12.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.21
            - interface: eth1/5
              forward_router_address: 20.0.0.29
          - dest: 192.168.14.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.21
            - interface: eth1/5
              forward_router_address: 20.0.0.29
          - dest: 192.168.16.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.21
            - interface: eth1/5
              forward_router_address: 20.0.0.29
          - dest: 209.165.201.0/24
            next_hops:
            - interface: eth1/3
              forward_router_address: 20.0.0.114

              


#################################
### Configure core2 interfaces ###
#################################

- name: Task to see config
  hosts: core2
  tasks:

  - name: Configure interfaces to layer3
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        description: Core2 to Core1 interface
        mode: layer3
      - name: Ethernet1/2
        description: Core2 to Core4 interface
        mode: layer3
      - name: Ethernet1/3
        description: Core2 to Core3 interface
        mode: layer3
      - name: Ethernet1/4
        description: Core2 to Dist3 interface
        mode: layer3
      - name: Ethernet1/5
        description: Core2 to Dist4 interface
        mode: layer3
      - name: Ethernet1/6
        description: Core2 to Dist5 interface
        mode: layer3
      - name: Ethernet1/7
        description: Core2 to Dist6 interface
        mode: layer3
      - name: Ethernet1/8
        description: Core2 to Dist7 interface
        mode: layer3
      - name: Ethernet1/9
        description: Core2 to Dist8 interface
        mode: layer3

  - name: Configure layer 3 interfaces
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: Ethernet1/1
        ipv4:
        - address: 20.0.0.102/30
      - name: Ethernet1/2
        ipv4:
        - address: 20.0.0.118/30
      - name: Ethernet1/3
        ipv4:
        - address: 20.0.0.105/30
      - name: Ethernet1/4
        ipv4:
        - address: 20.0.0.18/30
      - name: Ethernet1/5
        ipv4:
        - address: 20.0.0.26/30
      - name: Ethernet1/6
        ipv4:
        - address: 20.0.0.38/30
      - name: Ethernet1/7
        ipv4:
        - address: 20.0.0.46/30
      - name: Ethernet1/8
        ipv4:
        - address: 20.0.0.54/30
      - name: Ethernet1/9
        ipv4:
        - address: 20.0.0.62/30
        

  - name: Bring up interfaces
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        enabled: true
      - name: Ethernet1/2
        enabled: true
      - name: Ethernet1/3
        enabled: true
      - name: Ethernet1/4
        enabled: true
      - name: Ethernet1/4
        enabled: true
      - name: Ethernet1/6
        enabled: true
      - name: Ethernet1/7
        enabled: true
      - name: Ethernet1/8
        enabled: true
      - name: Ethernet1/9
        enabled: true
        
  - name: Configure static routes to distribution and core
    cisco.nxos.nxos_static_routes:
      config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: 192.168.2.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.101
            - interface: eth1/2
              forward_router_address: 20.0.0.117
          - dest: 192.168.4.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.101
            - interface: eth1/2
              forward_router_address: 20.0.0.117
          - dest: 192.168.6.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.101
            - interface: eth1/2
              forward_router_address: 20.0.0.117
          - dest: 192.168.8.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.101
            - interface: eth1/2
              forward_router_address: 20.0.0.117
          - dest: 192.168.10.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.17
            - interface: eth1/5
              forward_router_address: 20.0.0.25
          - dest: 192.168.12.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.17
            - interface: eth1/5
              forward_router_address: 20.0.0.25
          - dest: 192.168.14.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.17
            - interface: eth1/5
              forward_router_address: 20.0.0.25
          - dest: 192.168.16.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.17
            - interface: eth1/5
              forward_router_address: 20.0.0.25
          - dest: 192.168.250.0/24
            next_hops:
            - interface: eth1/6
              forward_router_address: 20.0.0.37
            - interface: eth1/7
              forward_router_address: 20.0.0.45



#################################
### Configure core3 interfaces ###
#################################

- name: Task to see config
  hosts: core3
  tasks:

  - name: Configure interfaces to layer3
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        description: Core3 to Core4 interface
        mode: layer3
      - name: Ethernet1/2
        description: Core3 to Core2 interface
        mode: layer3
      - name: Ethernet1/3
        description: Core3 to Core1 interface
        mode: layer3
      - name: Ethernet1/4
        description: Core3 to Dist5 interface
        mode: layer3
      - name: Ethernet1/5
        description: Core3 to Dist6 interface
        mode: layer3
      - name: Ethernet1/6
        description: Core3 to Dist7 interface
        mode: layer3
      - name: Ethernet1/7
        description: Core3 to Dist8 interface
        mode: layer3
      - name: Ethernet1/8
        description: Core3 to Dist10 interface
        mode: layer3
      - name: Ethernet1/9
        description: Core2 to Dist9 interface
        mode: layer3

  - name: Configure layer 3 interfaces
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: Ethernet1/1
        ipv4:
        - address: 20.0.0.110/30
      - name: Ethernet1/2
        ipv4:
        - address: 20.0.0.106/30
      - name: Ethernet1/3
        ipv4:
        - address: 20.0.0.114/30
      - name: Ethernet1/4
        ipv4:
        - address: 20.0.0.34/30
      - name: Ethernet1/5
        ipv4:
        - address: 20.0.0.42/30
      - name: Ethernet1/6
        ipv4:
        - address: 20.0.0.50/30
      - name: Ethernet1/7
        ipv4:
        - address: 20.0.0.58/30
      - name: Ethernet1/8
        ipv4:
        - address: 20.0.0.78/30
      - name: Ethernet1/9
        ipv4:
        - address: 20.0.0.70/30
        

  - name: Bring up interfaces
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        enabled: true
      - name: Ethernet1/2
        enabled: true
      - name: Ethernet1/3
        enabled: true
      - name: Ethernet1/4
        enabled: true
      - name: Ethernet1/4
        enabled: true
      - name: Ethernet1/6
        enabled: true
      - name: Ethernet1/7
        enabled: true
      - name: Ethernet1/8
        enabled: true
      - name: Ethernet1/9
        enabled: true
        
  - name: Configure static routes to distribution and core
    cisco.nxos.nxos_static_routes:
      config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: 192.168.250.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.17
            - interface: eth1/5
              forward_router_address: 20.0.0.25
          - dest: 209.165.201.0/24
            next_hops:
            - interface: eth1/7
              forward_router_address: 20.0.0.57


#################################
### Configure core4 interfaces ###
#################################

- name: Task to see config
  hosts: core4
  tasks:

  - name: Configure interfaces to layer3
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        description: Core1 to Core2 interface
        mode: layer3
      - name: Ethernet1/2
        description: Core1 to Core4 interface
        mode: layer3
      - name: Ethernet1/3
        description: Core1 to Core3 interface
        mode: layer3
      - name: Ethernet1/4
        description: Core1 to Dist3 interface
        mode: layer3
      - name: Ethernet1/5
        description: Core1 to Dist3 interface
        mode: layer3
      - name: Ethernet1/6
        description: Core1 to Dist3 interface
        mode: layer3
      - name: Ethernet1/7
        description: Core1 to Dist3 interface
        mode: layer3
      - name: Ethernet1/8
        description: Core1 to Dist3 interface
        mode: layer3
      - name: Ethernet1/9
        description: Core1 to Dist1 interface
        mode: layer3

  - name: Configure layer 3 interfaces
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: Ethernet1/1
        ipv4:
        - address: 20.0.0.109/30
      - name: Ethernet1/2
        ipv4:
        - address: 20.0.0.98/30
      - name: Ethernet1/3
        ipv4:
        - address: 20.0.0.117/30
      - name: Ethernet1/4
        ipv4:
        - address: 20.0.0.74/30
      - name: Ethernet1/5
        ipv4:
        - address: 20.0.0.66/30
      - name: Ethernet1/6
        ipv4:
        - address: 20.0.0.94/30
      - name: Ethernet1/7
        ipv4:
        - address: 20.0.0.86/30
      - name: Ethernet1/8
        ipv4:
        - address: 20.0.0.6/30
      - name: Ethernet1/9
        ipv4:
        - address: 20.0.0.14/30

  - name: Bring up interfaces
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        enabled: true
      - name: Ethernet1/2
        enabled: true
      - name: Ethernet1/3
        enabled: true
      - name: Ethernet1/4
        enabled: true
      - name: Ethernet1/5
        enabled: true
      - name: Ethernet1/6
        enabled: true
      - name: Ethernet1/7
        enabled: true
      - name: Ethernet1/8
        enabled: true
      - name: Ethernet1/9
        enabled: true
       
  - name: Configure static routes to distribution and core
    cisco.nxos.nxos_static_routes:
      config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: 192.168.2.0/24
            next_hops:
            - interface: eth1/8
              forward_router_address: 20.0.0.5
            - interface: eth1/9
              forward_router_address: 20.0.0.13
          - dest: 192.168.4.0/24
            next_hops:
            - interface: eth1/8
              forward_router_address: 20.0.0.5
            - interface: eth1/9
              forward_router_address: 20.0.0.13
          - dest: 192.168.6.0/24
            next_hops:
            - interface: eth1/8
              forward_router_address: 20.0.0.5
            - interface: eth1/9
              forward_router_address: 20.0.0.13
          - dest: 192.168.8.0/24
            next_hops:
            - interface: eth1/8
              forward_router_address: 20.0.0.5
            - interface: eth1/9
              forward_router_address: 20.0.0.13
          - dest: 192.168.10.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.97
            - interface: eth1/3
              forward_router_address: 20.0.0.118
          - dest: 192.168.12.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.97
            - interface: eth1/3
              forward_router_address: 20.0.0.118
          - dest: 192.168.14.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.97
            - interface: eth1/3
              forward_router_address: 20.0.0.118
          - dest: 192.168.16.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.97
            - interface: eth1/3
              forward_router_address: 20.0.0.118
          - dest: 192.168.18.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.73
            - interface: eth1/5
              forward_router_address: 20.0.0.65
          - dest: 192.168.20.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.73
            - interface: eth1/5
              forward_router_address: 20.0.0.65
          - dest: 192.168.22.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.73
            - interface: eth1/5
              forward_router_address: 20.0.0.65
          - dest: 192.168.24.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.73
            - interface: eth1/5
              forward_router_address: 20.0.0.65
          - dest: 192.168.26.0/24
            next_hops:
            - interface: eth1/6
              forward_router_address: 20.0.0.93
            - interface: eth1/7
              forward_router_address: 20.0.0.85
          - dest: 192.168.28.0/24
            next_hops:
            - interface: eth1/6
              forward_router_address: 20.0.0.93
            - interface: eth1/7
              forward_router_address: 20.0.0.85
          - dest: 192.168.30.0/24
            next_hops:
            - interface: eth1/6
              forward_router_address: 20.0.0.93
            - interface: eth1/7
              forward_router_address: 20.0.0.85
          - dest: 192.168.32.0/24
            next_hops:
            - interface: eth1/6
              forward_router_address: 20.0.0.93
            - interface: eth1/7
              forward_router_address: 20.0.0.85






        
