---

- name: Configure Core Group
  hosts: core
  tasks:
  
  - name: Enable RESTCONF
    nxos_feature:
      feature: restconf   
      state: enabled
      
  - name: Enable NETCONF
    nxos_feature:
      feature: netconf  
      state: enabled
      
  - name: Enable Bash-Shell
    nxos_feature:
      feature: bash-shell 
      state: enabled
      
  - name: Enable NXAPI
    nxos_feature:
      feature: nxapi
      state: enabled

  - name: Set ports NXAPI
    cisco.nxos.nxos_nxapi:
      enable_http: true
      enable_https: true
      http_port: 80
      https_port: 443

  - name: initiate file copy from device
    cisco.nxos.nxos_file_copy:
      file_pull: true
      remote_file: /home/developer/net_automation_aamargant/mtx-openconfig-all-1.0.0.0-9.2.3.lib32_n9000.rpm
      remote_scp_server: 10.10.20.50
      remote_scp_server_user: developer
      remote_scp_server_password: C1sco12345
      vrf: management

  - name: Install OpenConfig rpm package
    cisco.nxos.nxos_rpm:
      pkg: mtx-openconfig-all-1.0.0.0-9.2.3.lib32_n9000.rpm

#################################
### Configure core1 interfaces ###
#################################

- name: Configure Core 1
  hosts: core1
  tasks:

  - name: Configure interfaces to layer3
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        description: Core1 to Core2 interface
        mode: layer3
      - name: Ethernet1/2
        description: Core1 to Core4 interface
        mode: layer3
      - name: Ethernet1/3
        description: Core1 to Core3 interface
        mode: layer3
      - name: Ethernet1/4
        description: Core1 to Dist3 interface
        mode: layer3
      - name: Ethernet1/5
        description: Core1 to Dist4 interface
        mode: layer3
      - name: Ethernet1/6
        description: Core1 to Dist2 interface
        mode: layer3
      - name: Ethernet1/7
        description: Core1 to Dist1 interface
        mode: layer3
      - name: Ethernet1/8
        description: Core1 to Dist12 interface
        mode: layer3
      - name: Ethernet1/9
        description: Core1 to Dist11 interface
        mode: layer3

  - name: Configure layer 3 interfaces ip address
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: Ethernet1/1
        ipv4:
        - address: 20.0.0.101/30
      - name: Ethernet1/2
        ipv4:
        - address: 20.0.0.97/30
      - name: Ethernet1/3
        ipv4:
        - address: 20.0.0.113/30
      - name: Ethernet1/4
        ipv4:
        - address: 20.0.0.22/30
      - name: Ethernet1/5
        ipv4:
        - address: 20.0.0.30/30
      - name: Ethernet1/6
        ipv4:
        - address: 20.0.0.10/30
      - name: Ethernet1/7
        ipv4:
        - address: 20.0.0.2/30
      - name: Ethernet1/8
        ipv4:
        - address: 20.0.0.90/30
      - name: Ethernet1/9
        ipv4:
        - address: 20.0.0.82/30
        
  - name: Bring up interfaces
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        enabled: true
      - name: Ethernet1/2
        enabled: true
      - name: Ethernet1/3
        enabled: true
      - name: Ethernet1/4
        enabled: true
      - name: Ethernet1/5
        enabled: true
      - name: Ethernet1/6
        enabled: true
      - name: Ethernet1/7
        enabled: true
      - name: Ethernet1/8
        enabled: true
      - name: Ethernet1/9
        enabled: true
        
  - name: Configure static routes core-distribution and core-core
    cisco.nxos.nxos_static_routes:
      config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: 192.168.2.0/24
            next_hops:
            - interface: eth1/6
              forward_router_address: 20.0.0.9
            - interface: eth1/7
              forward_router_address: 20.0.0.1
          - dest: 192.168.4.0/24
            next_hops:
            - interface: eth1/7
              forward_router_address: 20.0.0.1
            - interface: eth1/6
              forward_router_address: 20.0.0.9
          - dest: 192.168.6.0/24
            next_hops:
            - interface: eth1/7
              forward_router_address: 20.0.0.1
            - interface: eth1/6
              forward_router_address: 20.0.0.9
          - dest: 192.168.8.0/24
            next_hops:
            - interface: eth1/7
              forward_router_address: 20.0.0.1
            - interface: eth1/6
              forward_router_address: 20.0.0.9
          - dest: 192.168.10.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.21
            - interface: eth1/5
              forward_router_address: 20.0.0.29
          - dest: 192.168.12.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.21
            - interface: eth1/5
              forward_router_address: 20.0.0.29
          - dest: 192.168.14.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.21
            - interface: eth1/5
              forward_router_address: 20.0.0.29
          - dest: 192.168.16.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 20.0.0.21
            - interface: eth1/5
              forward_router_address: 20.0.0.29
          - dest: 192.168.18.0/24
            next_hops:
            - interface: eth1/3
              forward_router_address: 20.0.0.114
            - interface: eth1/2
              forward_router_address: 20.0.0.98
          - dest: 192.168.20.0/24
            next_hops:
            - interface: eth1/3
              forward_router_address: 20.0.0.114
            - interface: eth1/2
              forward_router_address: 20.0.0.98
          - dest: 192.168.22.0/24
            next_hops:
            - interface: eth1/3
              forward_router_address: 20.0.0.114
            - interface: eth1/2
              forward_router_address: 20.0.0.98
          - dest: 192.168.24.0/24
            next_hops:
            - interface: eth1/3
              forward_router_address: 20.0.0.114
            - interface: eth1/2
              forward_router_address: 20.0.0.98
          - dest: 192.168.26.0/24
            next_hops:
            - interface: eth1/8
              forward_router_address: 20.0.0.89
            - interface: eth1/9
              forward_router_address: 20.0.0.81
          - dest: 192.168.28.0/24
            next_hops:
            - interface: eth1/8
              forward_router_address: 20.0.0.89
            - interface: eth1/9
              forward_router_address: 20.0.0.81
          - dest: 192.168.30.0/24
            next_hops:
            - interface: eth1/8
              forward_router_address: 20.0.0.89
            - interface: eth1/9
              forward_router_address: 20.0.0.81
          - dest: 192.168.32.0/24
            next_hops:
            - interface: eth1/8
              forward_router_address: 20.0.0.89
            - interface: eth1/9
              forward_router_address: 20.0.0.81
          - dest: 192.168.250.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.102
            - interface: eth1/2
              forward_router_address: 20.0.0.114
          - dest: 209.165.201.0/24
            next_hops:
            - interface: eth1/3
              forward_router_address: 20.0.0.114
            - interface: eth1/1
              forward_router_address: 20.0.0.102
