---

- name: Configure distribution layer spine 3
  hosts: dist_spine_4
  tasks:
        
  - name: Configure interfaces to layer 3
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        enabled: true
        mode: layer3
      - name: Ethernet1/2
        enabled: true
        mode: layer3  
      - name: Ethernet1/4
        enabled: true
        mode: layer3  
        

- name: Configure individual vlans and hsrp on dist3 and static routes
  hosts: dist8
  tasks:  
  
  - name: Configure static routes
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: Ethernet1/1
        ipv4:
          - address: 20.0.0.61/30
      - name: Ethernet1/2
        ipv4:
          - address: 20.0.0.57/30
      - name: Ethernet1/4
        ipv4:
          - address: 20.0.0.121/30
    
  - name: Configure static routes to core
    cisco.nxos.nxos_static_routes:
      config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: 192.168.2.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.4.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.6.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 209.165.201.0/24
            next_hops:
            - interface: eth1/4
              forward_router_address: 192.168.1.1
              
