---

- name: Configure distribution layer
  hosts: dist_spine_1 
  tasks:

  - name: Create VLANs
    cisco.nxos.nxos_vlans:
      config:
       - name: vlan3         
         vlan_id: 3
         state: active
       - name: vlan5
         vlan_id: 5
         state: activ
       - name: vlan9
         vlan_id: 9
         state: active
       - name: vlan14
         vlan_id: 14
         state: active

  - name: Enable interface-vlan
    nxos_feature:
      feature: interface-vlan    
      state: enabled
 
  - name: Configure VLANs
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: vlan 3
        ipv4:
          - address: 192.168.3.2/24
      - name: vlan 5
        ipv4:
          - address: 192.168.5.2/24

  - name: Configure HRSP 
    cisco.nxos.nxos_hsrp:
      group: 3
      vip: 192.168.3.1
      priority: 120
      interface: vlan10
      preempt: enabled

  - name: Configure trunk switchports
    cisco.nxos.nxos_l2_interfaces:   
      config:
      - name: Ethernet1/3
        mode: trunk  
      - name: Ethernet1/4
        mode: trunk

  - name: Enable vlans
    nxos_interface:
      name: vlan 3
      admin_state: up 
      name: vlan 5
      admin_state: up                            
