---

- name: Configure distribution layer
  hosts: dist_spine_1 
  tasks:

  - name: Create VLANs
    cisco.nxos.nxos_vlans:
      config:
       - name: vlan2         
         vlan_id: 2
         state: active
       - name: vlan4
         vlan_id: 4
         state: active
       - name: vlan6
         vlan_id: 6
         state: active
       - name: vlan8
         vlan_id: 8
         state: active

  - name: Enable interface-vlan
    nxos_feature:
      feature: interface-vlan    
      state: enabled
      
  - name: Enable HSRP
    nxos_feature:
      feature: hsrp
      state: enabled

  - name: Enable vlan 2
    cisco.nxos.nxos_interface:
      name: vlan 2
      admin_state: up

  - name: Enable vlan 4
    cisco.nxos.nxos_interface: 
      name: vlan 4
      admin_state: up

  - name: Enable vlan 6
    cisco.nxos.nxos_interface:    
      name: vlan 6
      admin_state: up

  - name: Enable vlan 8
    cisco.nxos.nxos_interface:
      name: vlan 8
      admin_state: up

  - name: Configure trunk switchports
    cisco.nxos.nxos_l2_interfaces:   
      config:
      - name: Ethernet1/3
        mode: trunk  
      - name: Ethernet1/4
        mode: trunk
      - name: Ethernet1/5
        mode: trunk
      - name: Ethernet1/6
        mode: trunk 
      - name: Ethernet1/7
        mode: trunk 
      
  - name: Configure interfaces to layer 3
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        enabled: true
        mode: layer3
      - name: Ethernet1/2
        enabled: true
        mode: layer3
        
      
- name: Configure individual vlans and hsrp on dist1
  hosts: dist1
  tasks:  
            
  - name: Configure VLANs
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: vlan 2
        ipv4:
          - address: 192.168.2.2/24
      - name: vlan 4
        ipv4:
          - address: 192.168.4.2/24
      - name: vlan 6
        ipv4:
          - address: 192.168.6.2/24
      - name: vlan 8
        ipv4:
          - address: 192.168.8.2/24
      - name: Ethernet1/1
        ipv4:
          - address: 20.0.0.1/30
      - name: Ethernet1/2
        ipv4:
          - address: 20.0.0.2/30
          
  - name: Configure HRSP vlan 2
    cisco.nxos.nxos_hsrp:
      group: 2
      vip: 192.168.2.1
      priority: 120
      interface: vlan 2
      preempt: enabled
      
  - name: Configure HRSP vlan 4
    cisco.nxos.nxos_hsrp:
      group: 4
      vip: 192.168.4.1
      priority: 100
      interface: vlan 4
      preempt: enabled

  - name: Configure HRSP vlan 6
    cisco.nxos.nxos_hsrp:
      group: 6
      vip: 192.168.6.1
      priority: 120
      interface: vlan 6
      preempt: enabled
      
  - name: Configure HRSP vlan 8
    cisco.nxos.nxos_hsrp:
      group: 8
      vip: 192.168.8.1
      priority: 100
      interface: vlan 8
      preempt: enabled
      
- name: Configure individual vlans and hsrp on dist2
  hosts: dist2
  tasks:  
            
  - name: Configure VLANs
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: vlan 2
        ipv4:
          - address: 192.168.2.3/24
      - name: vlan 4
        ipv4:
          - address: 192.168.4.3/24
      - name: vlan 6
        ipv4:
          - address: 192.168.6.3/24
      - name: vlan 8
        ipv4:
          - address: 192.168.8.3/24
      - name: Ethernet1/1
        ipv4:
          - address: 20.0.0.5/30
      - name: Ethernet1/2
        ipv4:
          - address: 20.0.0.6/30
          
  - name: Configure HRSP vlan2
    cisco.nxos.nxos_hsrp:
      group: 2
      vip: 192.168.2.1
      priority: 100
      interface: vlan 2
      preempt: enabled
      
  - name: Configure HRSP vlan4
    cisco.nxos.nxos_hsrp:
      group: 4
      vip: 192.168.4.1
      priority: 120
      interface: vlan 4
      preempt: enabled

  - name: Configure HRSP vlan6
    cisco.nxos.nxos_hsrp:
      group: 6
      vip: 192.168.6.1
      priority: 100
      interface: vlan 6
      preempt: enabled
      
  - name: Configure HRSP vlan8
    cisco.nxos.nxos_hsrp:
      group: 8
      vip: 192.168.8.1
      priority: 120
      interface: vlan 8
      preempt: enabled
