---

- name: Configure distribution layer spine 5
  hosts: dist_spine_5
  tasks:
  
  - name: Enable interface-vlan
    nxos_feature:
      feature: interface-vlan    
      state: enabled
      
  - name: Enable RESTCONF
    nxos_feature:
      feature: restconf   
      state: enabled
      
  - name: Enable NETCONF
    nxos_feature:
      feature: netconf  
      state: enabled
      
  - name: Enable HSRP
    nxos_feature:
      feature: hsrp
      state: enabled
      
  - name: Enable Bash-Shell
    nxos_feature:
      feature: bash-shell 
      state: enabled
      
  - name: Enable NXAPI
    nxos_feature:
      feature: nxapi
      state: enabled

  - name: Set ports NXAPI
    cisco.nxos.nxos_nxapi:
      enable_http: true
      enable_https: true
      http_port: 80
      https_port: 443
      
  - name: Copying netconf configuration package from Devbox to local machine
    cisco.nxos.nxos_file_copy:
      file_pull: true
      remote_file: /home/developer/net_automation_aamargant/mtx-openconfig-all-1.0.0.0-9.2.3.lib32_n9000.rpm
      remote_scp_server: 10.10.20.50
      remote_scp_server_user: developer
      remote_scp_server_password: C1sco12345
      vrf: management

  - name: Installing netconf configuration rpm package
    cisco.nxos.nxos_rpm:
      pkg: mtx-openconfig-all-1.0.0.0-9.2.3.lib32_n9000.rpm

  - name: Create VLANs
    cisco.nxos.nxos_vlans:
      config:
       - name: vlan18       
         vlan_id: 18
         state: active
       - name: vlan20
         vlan_id: 20
         state: active
       - name: vlan22
         vlan_id: 2
         state: active
       - name: vlan24
         vlan_id: 24
         state: active

  - name: Enable vlan 18
    cisco.nxos.nxos_interface:
      name: vlan 18
      admin_state: up

  - name: Enable vlan 20
    cisco.nxos.nxos_interface: 
      name: vlan 20
      admin_state: up

  - name: Enable vlan 22
    cisco.nxos.nxos_interface:    
      name: vlan 22
      admin_state: up

  - name: Enable vlan 24
    cisco.nxos.nxos_interface:
      name: vlan 24
      admin_state: up

  - name: Configure trunk switchports
    cisco.nxos.nxos_l2_interfaces:   
      config:
      - name: Ethernet1/3
        mode: trunk  
      - name: Ethernet1/4
        mode: trunk
      - name: Ethernet1/5
        mode: trunk
      - name: Ethernet1/6
        mode: trunk 
      - name: Ethernet1/7
        mode: trunk 
        

- name: Configure individual vlans and hsrp on dist9 and static routes
  hosts: dist9
  tasks:
  
  - name: Configure interfaces to layer 3
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        description: Dist9 to Core4 interface
        enabled: true
        mode: layer3
      - name: Ethernet1/2
        description: Dist9 to Core3 interface
        enabled: true
        mode: layer3
      - name: Ethernet1/3
        description: Dist9 to Access16 interface
      - name: Ethernet1/4
        description: Dist9 to Access15 interface
      - name: Ethernet1/5
        description: Dist9 to Access14 interface
      - name: Ethernet1/6
        description: Dist9 to Access13 interface
      - name: Ethernet1/7
        description: Dist9 to Dist10 interface   
            
  - name: Configure VLANs
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: vlan 18
        ipv4:
          - address: 192.168.18.2/24
      - name: vlan 20
        ipv4:
          - address: 192.168.20.2/24
      - name: vlan 22
        ipv4:
          - address: 192.168.22.2/24
      - name: vlan 24
        ipv4:
          - address: 192.168.24.2/24
      - name: Ethernet1/1
        ipv4:
          - address: 20.0.0.69/30
      - name: Ethernet1/2
        ipv4:
          - address: 20.0.0.65/30
        
          
  - name: Configure HRSP vlan 18
    cisco.nxos.nxos_hsrp:
      group: 18
      vip: 192.168.18.1
      priority: 120
      interface: vlan 18
      preempt: enabled
      
  - name: Configure HRSP vlan 20
    cisco.nxos.nxos_hsrp:
      group: 20
      vip: 192.168.20.1
      priority: 100
      interface: vlan 20
      preempt: enabled

  - name: Configure HRSP vlan 22
    cisco.nxos.nxos_hsrp:
      group: 22
      vip: 192.168.22.1
      priority: 120
      interface: vlan 22
      preempt: enabled
      
  - name: Configure HRSP vlan 24
    cisco.nxos.nxos_hsrp:
      group: 24
      vip: 192.168.24.1
      priority: 100
      interface: vlan 24
      preempt: enabled
    
  - name: Configure static routes to core
    cisco.nxos.nxos_static_routes:
      config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: 192.168.2.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 192.168.4.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 192.168.6.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 192.168.8.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 192.168.10.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 192.168.12.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 192.168.14.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 192.168.16.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 192.168.26.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 192.168.28.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 192.168.30.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 192.168.32.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 192.168.250.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
          - dest: 209.165.201.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.70
            - interface: eth1/1
              forward_router_address: 20.0.0.66
      
- name: Configure individual vlans and hsrp on dist10
  hosts: dist10
  tasks:
  
  - name: Configure interfaces to layer 3
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        description: Dist10 to Core4 interface
        enabled: true
        mode: layer3
      - name: Ethernet1/2
        description: Dist10 to Core3 interface
        enabled: true
        mode: layer3
      - name: Ethernet1/3
        description: Dist10 to Access16 interface
      - name: Ethernet1/4
        description: Dist10 to Access15 interface
      - name: Ethernet1/5
        description: Dist10 to Access14 interface
      - name: Ethernet1/6
        description: Dist10 to Access13 interface
      - name: Ethernet1/7
        description: Dist10 to Dist9 interface 
            
  - name: Configure VLANs
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: vlan 18
        ipv4:
          - address: 192.168.18.3/24
      - name: vlan 20
        ipv4:
          - address: 192.168.20.3/24
      - name: vlan 22
        ipv4:
          - address: 192.168.22.3/24
      - name: vlan 24
        ipv4:
          - address: 192.168.24.3/24
      - name: Ethernet1/1
        ipv4:
          - address: 20.0.0.73/30
      - name: Ethernet1/2
        ipv4:
          - address: 20.0.0.77/30
          
  - name: Configure HRSP vlan18
    cisco.nxos.nxos_hsrp:
      group: 18
      vip: 192.168.18.1
      priority: 100
      interface: vlan 18
      preempt: enabled
      
  - name: Configure HRSP vlan20
    cisco.nxos.nxos_hsrp:
      group: 20
      vip: 192.168.20.1
      priority: 120
      interface: vlan 20
      preempt: enabled

  - name: Configure HRSP vlan22
    cisco.nxos.nxos_hsrp:
      group: 22
      vip: 192.168.22.1
      priority: 100
      interface: vlan 22
      preempt: enabled
      
  - name: Configure HRSP vlan24
    cisco.nxos.nxos_hsrp:
      group: 24
      vip: 192.168.24.1
      priority: 120
      interface: vlan 24
      preempt: enabled
     
  - name: Configure static routes to distribution
    cisco.nxos.nxos_static_routes:
      config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: 192.168.2.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
          - dest: 192.168.4.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
          - dest: 192.168.6.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
          - dest: 192.168.8.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.26
            - interface: eth1/1
              forward_router_address: 20.0.0.30
          - dest: 192.168.10.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
          - dest: 192.168.12.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
          - dest: 192.168.14.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
          - dest: 192.168.16.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
          - dest: 192.168.26.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
          - dest: 192.168.28.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
          - dest: 192.168.30.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
          - dest: 192.168.32.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
          - dest: 192.168.250.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
          - dest: 209.165.201.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.78
            - interface: eth1/1
              forward_router_address: 20.0.0.74
