---

- name: Configure distribution layer spine 3
  hosts: dist_spine_3
  tasks:

  - name: Create VLANs
    cisco.nxos.nxos_vlans:
      config:
       - name: vlan250        
         vlan_id: 250
         state: active

  - name: Enable interface-vlan
    nxos_feature:
      feature: interface-vlan    
      state: enabled
      
  - name: Enable RESTCONF
    nxos_feature:
      feature: restconf   
      state: enabled
      
  - name: Enable NETCONF
    nxos_feature:
      feature: netconf  
      state: enabled
      
  - name: Enable Bash-Shell
    nxos_feature:
      feature: bash-shell 
      state: enabled
      
  - name: Copying netconf configuration package from Devbox to local machine
    cisco.nxos.nxos_file_copy:
      file_pull: true
      remote_file: /home/developer/cml_ansible/mtx-openconfig-all-1.0.0.0-9.2.3.lib32_n9000.rpm
      remote_scp_server: 10.10.20.50
      remote_scp_server_user: developer
      remote_scp_server_password: C1sco12345
      vrf: management

  - name: Installing netconf configuration rpm package
    cisco.nxos.nxos_rpm:
      pkg: mtx-openconfig-all-1.0.0.0-9.2.3.lib32_n9000.rpm
      
  - name: Enable HSRP
    nxos_feature:
      feature: hsrp
      state: enabled

  - name: Enable vlan 250
    cisco.nxos.nxos_interface:
      name: vlan 250
      admin_state: up

  - name: Configure trunk switchports
    cisco.nxos.nxos_l2_interfaces:   
      config:
      - name: Ethernet1/3
        mode: trunk  
      - name: Ethernet1/4
        mode: trunk
      - name: Ethernet1/5
        mode: trunk
        
  - name: Configure interfaces to layer 3
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        enabled: true
        mode: layer3
      - name: Ethernet1/2
        enabled: true
        mode: layer3    
        

- name: Configure individual vlans and hsrp on dist5 and static routes
  hosts: dist5
  tasks:  
            
  - name: Configure VLANs and static routes
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: vlan 250
        ipv4:
          - address: 192.168.250.2/24
      - name: Ethernet1/1
        ipv4:
          - address: 20.0.0.37/30
      - name: Ethernet1/2
        ipv4:
          - address: 20.0.0.33/30
        
  - name: Configure HRSP vlan 250
    cisco.nxos.nxos_hsrp:
      group: 250
      vip: 192.168.250.1
      priority: 120
      interface: vlan 250
      preempt: enabled
    
  - name: Configure static routes to core
    cisco.nxos.nxos_static_routes:
      config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: 192.168.2.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.4.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.6.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.8.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.10.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.12.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.14.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.16.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.18.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.20.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.22.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.38
            - interface: eth1/2
              forward_router_address: 20.0.0.34
          - dest: 192.168.24.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.38
            - interface: eth1/2
              forward_router_address: 20.0.0.34
          - dest: 192.168.26.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.28.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.30.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 192.168.32.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
          - dest: 209.165.201.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.34
            - interface: eth1/1
              forward_router_address: 20.0.0.38
      
- name: Configure individual vlans and hsrp on dist6
  hosts: dist6
  tasks:  
            
  - name: Configure VLANs and static routes
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: vlan 250
        ipv4:
          - address: 192.168.250.3/24
      - name: Ethernet1/1
        ipv4:
          - address: 20.0.0.45/30
      - name: Ethernet1/2
        ipv4:
          - address: 20.0.0.41/30
          
  - name: Configure HRSP vlan250
    cisco.nxos.nxos_hsrp:
      group: 10
      vip: 192.168.250.1
      priority: 100
      interface: vlan 250
      preempt: enabled
      
  - name: Configure static routes to core
    cisco.nxos.nxos_static_routes:
      config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: 192.168.2.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.4.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.6.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.8.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.10.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.12.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.14.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.16.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.18.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.20.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.22.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.24.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.26.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.28.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.30.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 192.168.32.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
          - dest: 209.165.201.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.42
            - interface: eth1/1
              forward_router_address: 20.0.0.46
