---

- name: Configure distribution layer spine 1
  hosts: dist_spine_1 
  tasks:
  
  - name: Enable interface-vlan
    nxos_feature:
      feature: interface-vlan    
      state: enabled
      
  - name: Enable HSRP
    nxos_feature:
      feature: hsrp
      state: enabled
      
  - name: Enable RESTCONF
    nxos_feature:
      feature: restconf   
      state: enabled
      
  - name: Enable NETCONF
    nxos_feature:
      feature: netconf  
      state: enabled
      
  - name: Enable Bash-Shell
    nxos_feature:
      feature: bash-shell 
      state: enabled
      
  - name: Copying netconf configuration package from Devbox to local machine
    cisco.nxos.nxos_file_copy:
      file_pull: true
      remote_file: /home/developer/cml_ansible/mtx-openconfig-all-1.0.0.0-9.2.3.lib32_n9000.rpm
      remote_scp_server: 10.10.20.50
      remote_scp_server_user: developer
      remote_scp_server_password: C1sco12345
      vrf: management

  - name: Installing netconf configuration rpm package
    cisco.nxos.nxos_rpm:
      pkg: mtx-openconfig-all-1.0.0.0-9.2.3.lib32_n9000.rpm

  - name: Create VLANs
    cisco.nxos.nxos_vlans:
      config:
       - name: vlan2         
         vlan_id: 2
         state: active
       - name: vlan4
         vlan_id: 4
         state: active
       - name: vlan6
         vlan_id: 6
         state: active
       - name: vlan8
         vlan_id: 8
         state: active

  - name: Enable vlan 2
    cisco.nxos.nxos_interface:
      name: vlan 2
      admin_state: up

  - name: Enable vlan 4
    cisco.nxos.nxos_interface: 
      name: vlan 4
      admin_state: up

  - name: Enable vlan 6
    cisco.nxos.nxos_interface:    
      name: vlan 6
      admin_state: up

  - name: Enable vlan 8
    cisco.nxos.nxos_interface:
      name: vlan 8
      admin_state: up

  - name: Configure trunk switchports
    cisco.nxos.nxos_l2_interfaces:   
      config:
      - name: Ethernet1/3
        mode: trunk  
      - name: Ethernet1/4
        mode: trunk
      - name: Ethernet1/5
        mode: trunk
      - name: Ethernet1/6
        mode: trunk 
      - name: Ethernet1/7
        mode: trunk 
      
      
- name: Configure individual vlans and hsrp on dist1
  hosts: dist1
  tasks:  
  
  - name: Configure interfaces to layer 3 and setting descriptions
    cisco.nxos.nxos_interfaces:
      config:
      - name: Ethernet1/1
        description: Dist1 to Core1 interface
        enabled: true
        mode: layer3
      - name: Ethernet1/2
        description: Dist1 to Core4 interface
        enabled: true
        mode: layer3
      - name: Ethernet1/3
        description: Dist1 to Access1 interface
      - name: Ethernet1/4
        description: Dist1 to Access2 interface
      - name: Ethernet1/5
        description: Dist1 to Access3 interface
      - name: Ethernet1/6
        description: Dist1 to Access4 interface
      - name: Ethernet1/7
        description: Dist1 to Dist2 interface
            
  - name: Configure VLANs and static routes
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: vlan 2
        ipv4:
          - address: 192.168.2.2/24
      - name: vlan 4
        ipv4:
          - address: 192.168.4.2/24
      - name: vlan 6
        ipv4:
          - address: 192.168.6.2/24
      - name: vlan 8
        ipv4:
          - address: 192.168.8.2/24
      - name: Ethernet1/1
        ipv4:
          - address: 20.0.0.1/30
      - name: Ethernet1/2
        ipv4:
          - address: 20.0.0.5/30
          
  - name: Configure HRSP vlan 2
    cisco.nxos.nxos_hsrp:
      group: 2
      vip: 192.168.2.1
      priority: 120
      interface: vlan 2
      preempt: enabled
      
  - name: Configure HRSP vlan 4
    cisco.nxos.nxos_hsrp:
      group: 4
      vip: 192.168.4.1
      priority: 100
      interface: vlan 4
      preempt: enabled

  - name: Configure HRSP vlan 6
    cisco.nxos.nxos_hsrp:
      group: 6
      vip: 192.168.6.1
      priority: 120
      interface: vlan 6
      preempt: enabled
      
  - name: Configure HRSP vlan 8
    cisco.nxos.nxos_hsrp:
      group: 8
      vip: 192.168.8.1
      priority: 100
      interface: vlan 8
      preempt: enabled
      
  - name: Configure static routes to core
    cisco.nxos.nxos_static_routes:
      config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: 192.168.10.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.6
            - interface: eth1/1
              forward_router_address: 20.0.0.2
          - dest: 192.168.12.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.6
            - interface: eth1/1
              forward_router_address: 20.0.0.2
          - dest: 192.168.14.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.6
            - interface: eth1/1
              forward_router_address: 20.0.0.2
          - dest: 192.168.16.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.6
            - interface: eth1/1
              forward_router_address: 20.0.0.2
          - dest: 192.168.18.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.2
            - interface: eth1/2
              forward_router_address: 20.0.0.6
          - dest: 192.168.20.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.2
            - interface: eth1/2
              forward_router_address: 20.0.0.6
          - dest: 192.168.22.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.2
            - interface: eth1/2
              forward_router_address: 20.0.0.6
          - dest: 192.168.24.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.2
            - interface: eth1/2
              forward_router_address: 20.0.0.6
          - dest: 192.168.26.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.2
            - interface: eth1/2
              forward_router_address: 20.0.0.6
          - dest: 192.168.28.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.2
            - interface: eth1/2
              forward_router_address: 20.0.0.6
          - dest: 192.168.30.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.6
            - interface: eth1/1
              forward_router_address: 20.0.0.2
          - dest: 192.168.32.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.6
            - interface: eth1/1
              forward_router_address: 20.0.0.2
          - dest: 192.168.250.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.6
            - interface: eth1/1
              forward_router_address: 20.0.0.2
          - dest: 209.165.201.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.6
            - interface: eth1/1
              forward_router_address: 20.0.0.2
                 
                 
- name: Configure individual vlans and hsrp on dist2
  hosts: dist2
  tasks:  
            
  - name: Configure VLANs and static routes
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: vlan 2
        ipv4:
          - address: 192.168.2.3/24
      - name: vlan 4
        ipv4:
          - address: 192.168.4.3/24
      - name: vlan 6
        ipv4:
          - address: 192.168.6.3/24
      - name: vlan 8
        ipv4:
          - address: 192.168.8.3/24
      - name: Ethernet1/1
        ipv4:
          - address: 20.0.0.9/30
      - name: Ethernet1/2
        ipv4:
          - address: 20.0.0.13/30
          
  - name: Configure HRSP vlan2
    cisco.nxos.nxos_hsrp:
      group: 2
      vip: 192.168.2.1
      priority: 100
      interface: vlan 2
      preempt: enabled
      
  - name: Configure HRSP vlan4
    cisco.nxos.nxos_hsrp:
      group: 4
      vip: 192.168.4.1
      priority: 120
      interface: vlan 4
      preempt: enabled

  - name: Configure HRSP vlan6
    cisco.nxos.nxos_hsrp:
      group: 6
      vip: 192.168.6.1
      priority: 100
      interface: vlan 6
      preempt: enabled
      
  - name: Configure HRSP vlan8
    cisco.nxos.nxos_hsrp:
      group: 8
      vip: 192.168.8.1
      priority: 120
      interface: vlan 8
      preempt: enabled
      
  - name: Configure static routes to core
    cisco.nxos.nxos_static_routes:
      config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: 192.168.10.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.14
            - interface: eth1/1
              forward_router_address: 20.0.0.10
          - dest: 192.168.12.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.14
            - interface: eth1/1
              forward_router_address: 20.0.0.10
          - dest: 192.168.14.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.14
            - interface: eth1/1
              forward_router_address: 20.0.0.10
          - dest: 192.168.16.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.14
            - interface: eth1/1
              forward_router_address: 20.0.0.10
          - dest: 192.168.18.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.10
            - interface: eth1/2
              forward_router_address: 20.0.0.14
          - dest: 192.168.20.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.10
            - interface: eth1/2
              forward_router_address: 20.0.0.14
          - dest: 192.168.22.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.10
            - interface: eth1/2
              forward_router_address: 20.0.0.14
          - dest: 192.168.24.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.10
            - interface: eth1/2
              forward_router_address: 20.0.0.14
          - dest: 192.168.26.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.10
            - interface: eth1/2
              forward_router_address: 20.0.0.14
          - dest: 192.168.28.0/24
            next_hops:
            - interface: eth1/1
              forward_router_address: 20.0.0.10
            - interface: eth1/2
              forward_router_address: 20.0.0.14
          - dest: 192.168.30.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.14
            - interface: eth1/1
              forward_router_address: 20.0.0.10
          - dest: 192.168.32.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.14
            - interface: eth1/1
              forward_router_address: 20.0.0.10
          - dest: 192.168.250.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.14
            - interface: eth1/1
              forward_router_address: 20.0.0.10
          - dest: 209.165.201.0/24
            next_hops:
            - interface: eth1/2
              forward_router_address: 20.0.0.14
            - interface: eth1/1
              forward_router_address: 20.0.0.10
