---

############################################################
#  Enble Config Logging
############################################################

- name: Task to see config
  hosts: lab
  tasks:
   - name: Gather only the config and default facts
     cisco.ios.ios_facts:
      gather_subset:
      - config
